import { Box, CssBaseline, Stack } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import React from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <AppRouterCacheProvider>
          <Stack
            direction="column"
            alignItems="center"
            sx={{ height: "100vh" }}
          >
            <Stack component={"header"} direction="row" spacing={2}>
              Header goes here
            </Stack>
            <Box
              component={"main"}
              sx={{ flexGrow: 1, width: "100%", p: 2, display: "flex", flexDirection: "column", alignItems: "center" }}
            >
              {children}
            </Box>
            <Stack component={"footer"} direction="row" spacing={2}>
              Footer goes here
            </Stack>
          </Stack>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
