import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <ul style={{display: "flex", flexDirection: "row", gap: 40}}>
              <li>
                <Link href={"/"}>Domov</Link>
              </li>
              <li>
                <Link href={"/prihlasenie"}>Prihlasit sa</Link>
              </li>
              <li>
                <Link href={"/registracia"}>Registrácia</Link>
              </li>
              <li>
                <Link href={"/dashboard"}>Dashboard</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        <footer>
          <p>&copy; 2024</p>
        </footer>
      </body>
    </html>
  );
}
