import { Box, Stack } from "@mui/material";
import type { Metadata } from "next";
import { EntityProvider } from "../context/EntityContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { getEntityDataFromServerCookies } from "@/lib/actions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //context neprezije pri refreshi stranky,
  //takze nacitam pouzivatela z cookies
  let entityData = await getEntityDataFromServerCookies();

  return (
    <html lang="en">
      <body style={{ height: "100%", margin: 0 }}>
        <EntityProvider initialEntity={entityData}>
          <Stack direction={"column"} minHeight={"100vh"} width={"100%"}>
            <Header/>
            <Box component="main" sx={{ flexGrow: 1, padding: 2, minHeight: "100%", width: "100%", boxSizing: "border-box",  /* backgroundColor: "blue" */ }}>
              {children}
            </Box>
            <Footer />
          </Stack>
        </EntityProvider>
      </body>
    </html>
  );
}
